urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
import webcast.views
import webcast.api

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', webcast.views.index),
    (r'^channel/(?P<channel_id>.*)$', webcast.views.channel),
    (r'^api/channels', webcast.api.channels),
    (r'^api/entries', webcast.api.entries),
    (r'^admin/updater$', webcast.views.updater),
    (r'^admin/start_updater/$', webcast.views.start_updater),
    (r'^admin/stop_updater/$', webcast.views.stop_updater),
    (r'^admin/update_now/$', webcast.views.update_now),
    url(r'^admin/', include(admin.site.urls)),
    (r'^common/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/common'}),
    (r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/images'}),
    # Example:
    # (r'^showbox/', include('foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
)

webcast/models.py
from django.db import models
import feedparser
import time
from datetime import datetime, timedelta
from webcast.scheduler import Scheduler
from django.db import IntegrityError
from django.conf import settings
from django.db import transaction

class Channel(models.Model):
    seq = models.IntegerField(default=99)
    name = models.CharField(max_length=100, unique=True)
    
    def __unicode__(self):
        return self.name 
    
class Feed(models.Model):
    url = models.CharField(max_length=500)
    title = models.CharField(max_length=500, null=True)
    channel = models.ForeignKey(Channel)
    
    def __unicode__(self):
        return '[' + self.channel.name + '] ' + self.title + ' ---- ' + self.url 

class Entry(models.Model):
    feed = models.ForeignKey(Feed)
    link = models.CharField(max_length=500)
    title = models.CharField(max_length=500)
    updated_at = models.DateTimeField()
    screenshot_path = models.CharField(max_length=500)
    def __unicode__(self):
        return self.link 

class UpdateLog(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    count = models.IntegerField()
    
class CastUpdater(object):
    instance = None
    PERIOD = 300
    
    @staticmethod
    def getInstance():
        if not CastUpdater.instance:
            CastUpdater.instance = CastUpdater()
        return CastUpdater.instance

    def __init__(self):
        self.sched = Scheduler(self.update, CastUpdater.PERIOD)
        self.recent_entries = []
    
    def start(self):
        self.sched.start()
        self.next_update_time = datetime.today() + timedelta(seconds=CastUpdater.PERIOD)
        
    def running(self):
        return self.sched.timer != None

    def update(self):
        self.last_update_time = datetime.today()
        self.next_update_time = datetime.today() + timedelta(seconds=CastUpdater.PERIOD)
        self.recent_entries = []
        
        feeds = Feed.objects.all()
        for feed in feeds:
            d = feedparser.parse(feed.url)
            print feed.url
            feed.title = d.feed.title
            feed.save()
            
            for e in d.entries:
                updated_at = datetime.today()
                if 'updated_parsed' in e:
                    updated_at = datetime.fromtimestamp((time.mktime(e.updated_parsed))) + timedelta(hours=9)
                
                link = e.link
                if '/http://' in e.link:
                    link = link[link.find('/http://') + 1:]
                try:
                    Entry.objects.get(link=link)
                except Entry.MultipleObjectsReturned:
                    pass
                except Entry.DoesNotExist:
                    entry = Entry.objects.create(feed=feed, title=e.title, link=link, updated_at=updated_at)
                    self.recent_entries.append(entry)
    
        UpdateLog.objects.create(count=len(self.recent_entries))
    
    def count(self):
        if not self.recent_entries: return 0
        
        return len(self.recent_entries)

webcast/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from webcast.models import *
from datetime import timedelta

def index(req):
    entries = Entry.objects.filter(updated_at__gt=datetime.today() - timedelta(days=2)).order_by('-updated_at')
    channels = Channel.objects.all().order_by('seq')
    return render_to_response('index.html', locals())

def channel(req, channel_id):
    channel_id=int(channel_id)
    entries = Entry.objects.filter(feed__in=Channel.objects.get(id=channel_id).feed_set.all()).filter(updated_at__gt=datetime.today() - timedelta(days=2)).order_by('-updated_at')
    channels = Channel.objects.all().order_by('seq')
    return render_to_response('index.html', locals())

def refresh(req):
#    feeds = update_cast()
    return render_to_response('update_cast.html', locals())

def updater(req):
    updater = CastUpdater.getInstance()
    return render_to_response('updater.html', locals())

def start_updater(req):
    updater = CastUpdater.getInstance()
    updater.start()
    return HttpResponseRedirect('/admin/updater')

def stop_updater(req):
    updater = CastUpdater.getInstance()
    updater.stop()
    return HttpResponseRedirect('/admin/updater')

def update_now(req):
    updater = CastUpdater.getInstance()
    updater.update()
    return HttpResponseRedirect('/admin/updater')

if settings.AUTO_UPDATE_ON_STARTUP: CastUpdater.getInstance().start()

webcast/templates/index.html
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>멍 캐스트 - 가만히 앉아서 보는 인터넷</title>
<link rel="stylesheet" type="text/css" href="/common/style.css" />

<script type="text/javascript" src="/common/prototype.js"></script>
<script type="text/javascript" src="/common/effects.js"></script>
<script type="text/javascript">
var entryIndex = 0;
var period = 20;
var timeElapsed = 0;
var interval = 1;
var pe;

function showEntry(index) {
	var link = $('entries').down('li a', index)
	$('showbox').down('iframe').src = link.href
	$('currentCast').href = link.href
	$('currentCast').innerHTML = link.innerHTML

	$$('#entries li').each(function(elem) { elem.removeClassName('current'); })
	$('entries').down('li', index).addClassName('current')
	$('entries').down('li', index).scrollIntoView();

	$('alarm').hide()
}

function play() {
	if (pe) return;

	timeElapsed = 0;
	
	pe = new PeriodicalExecuter(function(pe) {
		timeElapsed += interval;
//		$('timeElapsed').style.width = timeElapsed / period * 100 + '%';
		$('alarm').down('span').innerHTML = period - timeElapsed
		if (timeElapsed >= period - 5 && !$('alarm').visible()) {
			showAlarm()
		} else if (timeElapsed < period + interval && timeElapsed > period - interval) {
			timeElapsed = 0;
			showEntry(++entryIndex);
		}  
	}, interval);
	$('autoPlayButton').firstChild.src='/images/running.gif'
}

function pause() {
	if (pe)	pe.stop();
	pe = null;
	$('autoPlayButton').firstChild.src='/images/stopped.gif'
	$('alarm').hide();
}

function togglePlay() {
	if (pe) {
		pause();
	} else {
		play();
	}
}

function showAlarm() {
	$('alarm').appear({to: 0.8});
//	$('alarm').style.top = $('showFrame').cumulativeOffset().top + 'px';
	$('alarm').style.left = $('showFrame').cumulativeOffset().left + ($('showFrame').getWidth() - $('alarm').getWidth()) / 2 + 'px' ;
	$('alarm').style.top = $('showFrame').cumulativeOffset().top + ($('showFrame').getHeight() - $('alarm').getHeight()) / 2 + 'px';
//	$('alarm').style.left = (document.viewport.getWidth() - $('alarm').getWidth()) / 2 + 'px' ;
}

window.onload = function() {
	$('period').innerHTML = period
	$('entries').observe('click', function(evt) {
		evt.stop();
		var link;
		if (evt.element().nodeName.toLowerCase() == 'a') link = evt.element()
		else if (evt.element().nodeName.toLowerCase() == 'li') link = evt.element().firstChild
		else return;
		
		entryIndex = $$('#entries li').collect(function(elem, index) {
			return [elem, index]
		}).find(function(elem) {
			return elem[0] == link.parentNode
		})[1]
		timeElapsed = 0
		showEntry(entryIndex)
	})

	showEntry(0);
//	play();
//	resize();
}

function resize() {
//	var frame = $('showFrame')
	
//	var height = document.viewport.getHeight() - frame.cumulativeOffset().top - 30
//	frame.style.height = height + 'px'

//	var width = document.viewport.getWidth() - $('sidebar').getWidth() -30
//	frame.style.width = width + 'px'
//	$('controlPanel').style.width = width + 'px'

//	$('timeBar').style.width = width - 220 + 'px'
//	$('showFrame').style.height = $('showFrame').parentNode.getHeight() + 'px'
}
function addPeriod(n) {
	period += n
	$('period').innerHTML = period
}

//window.onresize = resize 

</script>
</head>

<body>
<table id="layout">
	<tbody>
		<tr class="controls" >
			<td style="width: 20px;">&nbsp;</td>
			<td style="width: 60px;"><button onclick="showEntry(--entryIndex)">&lt;이전</button></td>
			<td class="entryTitle" style="width: 400px; text-align: center"><a id="currentCast" href=""></a></td>
			<td style="width: 60px;"><button onclick="showEntry(++entryIndex); play();">다음&gt;</button></td>
			</td>
			<td style="text-align: right;">
				<span>자동보기</span>
				<span id="period"></span>초
				<button onclick="addPeriod(1)">+</button>
				<button onclick="addPeriod(-1)">-</button>
			</td>
			<td style="width: 30px; text-align: right">
				<button id="autoPlayButton" class="image" onclick="togglePlay(this)"><img src="/images/stopped.gif" style="width: 24px; height: 24px; position: relative; "/></button>
			</td>
			<td id="navigation">
				<a href="http://issue.mungcast.com">고객센터</a>
				&nbsp;
			</td>			

		</tr>
		<tr>
			<td colspan="6" id="showbox">
				<iframe id="showFrame" frameborder="0"></iframe>
			</td>
			<td id="sidebar" >
				<h2>채널</h2>
				<ul id="channel">
					<li {%if not channel_id%}class="current"{%endif%}><a href="/"">종합</a></li>
					{% for channel in channels %}
					<li {%ifequal channel_id channel.id %}class="current"{%endifequal%}><a href="/channel/{{channel.id}}">{{channel.name}}</a></li>
					{% endfor %}
				</ul>
				
				<h2>기사</h2>
				<ul id="entries">
					{% for entry in entries %}
					<li><a href="{{entry.link}}">{{entry.title}}</a></li>
					{% endfor %}
				</ul>
				<div>
					<a href="http://ecolemo.com"><img src="http://ecolemo.com/logo.png" style="border: none; width: 110px; height: 51px"/></a>
				</div>
			</td>
		</tr>
	</tbody>
</table>
</div>

<div id="alarm" style="display: none;" onclick="pause(); $('alarm').hide(); $('autoPlayButton').pulsate()">
	<h5>자동 넘김</h5>
	<span></span>
	<br/>
	<button class="image">멈춤</button>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-944094-2");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>

webcast/templates/update_cast.html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>심심풀이 땅콩</title>

<script type="text/javascript" src="/common/prototype.js"></script>

<body>
<ul id="urlList">
{% for feed in feeds %}
	<li>{{feed.url}}</li>
	<ul>
		{% for entry in feed.entry_set.all %}
			<li>{{entry.link}} {{entry.updated_at}}</li>
		{% endfor %}
	</ul>
{% endfor %}
</ul>
</body>
</html>

webcast/templates/updater.html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>심심풀이 땅콩</title>

<script type="text/javascript" src="/common/prototype.js"></script>

<body>
<h1>웹캐스트 업데이트 현황판</h1>
<h2>자동 업데이트</h2>
<div>
	<span>{{updater.running|yesno:"실행 중,중지됨"}}</span>
	<button onclick="location='/admin/start_updater'">실행</button>
	<button onclick="location='/admin/stop_updater'">중지</button>
	<br/>
	<span>마지막 업데이트 : {{updater.last_update_time}} {{updater.count}}건</span>
	<br/>
	<span>다음 업데이트 : {{updater.next_update_time}}</span>
	<button onclick="location='/admin/update_now'">지금 업데이트</button>
</div>
<h2>최근 업데이트 목록</h2>
<table>
	<thead>
		<tr>
			<th>기사</th>
			<th>피드</th>
			<th>업데이트</th>
		</tr>
	</thead>
	<tbody>
	{% for entry in updater.recent_entries %}
		<tr>
			<td><a href="{{entry.link}}">{{entry.title}}</a></td>
			<td><a href="{{entry.feed.link}}">{{entry.feed.title}}</a></td>
			<td>{{entry.updated_at}}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
</body>
</html>